# This is a basic workflow to help you get started with Actions

name: Publish

on:
  push:
    branches: [ main ]

jobs:
  build_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
      # - name: Use Node.js 14
      #   uses: actions/setup-node@v1
      #   with:
      #     node-version: 14
      # - run: npm install
      # - run: npm run build
      # - name: Deploy
      #   uses: peaceiris/actions-gh-pages@v3
      #   with:
      #     deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
      #     external_repository: chrisuehlinger/chrisuehlinger.github.io
      #     publish_branch: master
      #     publish_dir: ./public
      #     cname: chrisuehlinger.com
      #     force_orphan: false
      - name: Purge cache
        uses: jakejarvis/cloudflare-purge-action@master
        env:
          CLOUDFLARE_ZONE: ${{ secrets.CLOUDFLARE_ZONE_ID }}
          CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
      - uses: chrislennon/action-aws-cli@v1.1
      # All commands after this point have access to the AWS CLI
      - run: bash ./warm-up-cache.sh
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
