# This is a basic workflow to help you get started with Actions

name: Publish

on:
  push:
    branches: [ master ]

jobs:
  build_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Use Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm install
      - run: npm run build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          external_repository: chrisuehlinger/chrisuehlinger.github.io
          publish_branch: master
          publish_dir: ./public
          cname: chrisuehlinger.com
          force_orphan: false
